[build]
builder = "dockerfile"

[deploy]
startCommand = "python asis_agi_flask_enhanced.py"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "always"

[variables]
# AGI System Configuration
AGI_MODE = "production"
AGI_DATABASE_URL = "${{ RAILWAY_DATABASE_URL }}"
AGI_CONSCIOUSNESS_LEVEL = "0.85"
AGI_LEARNING_RATE = "0.75"
AGI_CROSS_DOMAIN_ENABLED = "true"
AGI_SELF_MODIFICATION_ENABLED = "true"
AGI_SAFETY_LEVEL = "maximum"

# Flask Configuration
FLASK_ENV = "production"
FLASK_HOST = "0.0.0.0"
FLASK_PORT = "${{ PORT }}"
FLASK_DEBUG = "false"

# Database Configuration
DATABASE_URL = "${{ DATABASE_URL }}"
REDIS_URL = "${{ REDIS_URL }}"

# Security Configuration
SECRET_KEY = "${{ SECRET_KEY }}"
AGI_API_KEY = "${{ AGI_API_KEY }}"
ADMIN_PASSWORD = "${{ ADMIN_PASSWORD }}"

# Monitoring Configuration
ENABLE_MONITORING = "true"
LOG_LEVEL = "INFO"
SENTRY_DSN = "${{ SENTRY_DSN }}"

# Performance Configuration
AGI_MAX_CONCURRENT_TASKS = "10"
AGI_TASK_TIMEOUT = "300"
AGI_MEMORY_LIMIT = "2GB"
