# Railway.app Configuration
# ASIS Research Platform

[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE" 
restartPolicyMaxRetries = 10
startCommand = "python -m gunicorn --bind 0.0.0.0:8000 --workers 1 --timeout 120 --worker-class uvicorn.workers.UvicornWorker app_minimal:app"

[settings]
generateDomain = true
