database:
  database: asis_dev
  host: localhost
  max_connections: 20
  password: dev_password
  pool_size: 5
  port: 5432
  username: dev_user
monitoring:
  grafana_port: 3001
  health_check_interval: 120
  log_level: DEBUG
  metrics_enabled: true
  prometheus_port: 9091
performance:
  batch_size: 50
  cache_ttl: 600
  cpu_limit_percent: 60
  max_workers: 2
  memory_limit_mb: 1024
  request_timeout: 60
redis:
  database: 2
  host: localhost
  max_connections: 20
  password: null
  port: 6379
security:
  allowed_origins:
  - http://localhost:3000
  jwt_expiry: 7200
  rate_limit_per_minute: 1000
  secret_key: dev_secret_key
  ssl_enabled: false
