database:
  database: asis_staging
  host: localhost
  max_connections: 50
  password: staging_password
  pool_size: 10
  port: 5432
  username: asis_user
monitoring:
  grafana_port: 3000
  health_check_interval: 60
  log_level: DEBUG
  metrics_enabled: true
  prometheus_port: 9090
performance:
  batch_size: 100
  cache_ttl: 1800
  cpu_limit_percent: 70
  max_workers: 4
  memory_limit_mb: 2048
  request_timeout: 45
redis:
  database: 1
  host: localhost
  max_connections: 50
  password: null
  port: 6379
security:
  allowed_origins:
  - http://staging.example.com
  jwt_expiry: 1800
  rate_limit_per_minute: 100
  secret_key: staging_secret_key
  ssl_enabled: false
